# Generated by Django 2.2.16 on 2023-03-28 18:29

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20230328_2053'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='author_cannot_subscribe',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='unique_author_user_following'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='author_cannot_subscribe'),
        ),
    ]
